apiVersion: v1
kind: Service
metadata:
  name: ai-devsecops-service
  namespace: ai-devsecops
spec:
  type: LoadBalancer

  selector:
    app: ai-devsecops-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000